### ISSUE TITLE
@types/pg-pool installs typings from DefinitelyTyped, not from here

### ISSUE THREAD

**Issue by ksiegel** [typed-typings/npm-pg-pool#2]
I used these typings back when I used the `typings` tool to manage my types.
Now that I'm on npm types, installing `@types/pg-pool` gets me the wrong set of typings. These are what I get: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/pg-pool/index.d.ts

Time for an npm re-release?

**Comment by blakeembrey** [comment]
These typings don't go to NPM, they are maintained separately. You can follow https://github.com/Microsoft/types-publisher/issues/4 for more info.
